[kadeploy-kernel][ppc64] fix mkfs.btrfs (add wipefs)

diff --git a/kadeploy3-deploy-kernel-buster-ppc64.yaml b/kadeploy3-deploy-kernel-buster-ppc64.yaml
--- a/kadeploy3-deploy-kernel-buster-ppc64.yaml
+++ b/kadeploy3-deploy-kernel-buster-ppc64.yaml
@@ -39,23 +39,29 @@ setup:
           cat <<'EOF' > /usr/local/sbin/mkfs-uuid-wrapper
           #!/bin/bash
           set -e
-          echo "Using mkfs uuid wrapper for $0"
+          echo "Using mkfs uuid wrapper for $0..."
           die() { echo "Error: $1." 1>&2 && exit 1; }
           FS=${0#*mkfs.}
-          [[ "$0" != "$FS" ]] || die "Could not guess FS"
-          REGEX="^/dev/sd(\w)([[:digit:]]+)$"
+          [[ "$0" != "$FS" ]] || die "Could not guess FS."
+          REGEX="^(/dev/sd(\w)([[:digit:]]+))$"
           for p in "$@"; do
             if [[ $p =~ $REGEX ]]; then
-              DISK=${BASH_REMATCH[1]}
-              PART=${BASH_REMATCH[2]}
+              DEV=${BASH_REMATCH[1]}
+              DISK=${BASH_REMATCH[2]}
+              PART=${BASH_REMATCH[3]}
             fi
           done
-          [[ -n "$DISK" ]] && [[ -n "$PART" ]] || die "Could not guess DISK and PARTITION"
+          [[ -n "$DISK" ]] && [[ -n "$PART" ]] || die "Could not guess DISK and PARTITION of $DEV."
           ord() { printf "%d" "'$1"; }
           printf -v UUID "12345678-0000-0000-%04d-%012d" $(($(ord $DISK) - $(ord "a") + 1 )) $PART
           declare -a OPT
           case $FS in
-            ext2|ext3|ext4|btrfs)
+            ext2|ext3|ext4)
+              OPT=("-U" $UUID)
+            ;;
+            btrfs)
+              echo "Wiping filesystem of $DEV so that $FS does not complain UUID is already used."
+              wipefs -a $DEV
               OPT=("-U" $UUID)
             ;;
             xfs)
@@ -65,7 +71,7 @@ setup:
               OPT=("--uuid" $UUID)
             ;;
             *)
-            die "Unhandled FILESYSTEM: $FS"
+            die "Unhandled FILESYSTEM: $FS."
             ;;
           esac
           echo exec -a $0 $0.distrib "${OPT[@]}" "$@" 
