[from_grid5000_environment] add capability to have an additional postinstall

diff --git a/steps/export/create_kadeploy_environment.yaml b/steps/export/create_kadeploy_environment.yaml
--- a/steps/export/create_kadeploy_environment.yaml
+++ b/steps/export/create_kadeploy_environment.yaml
@@ -10,6 +10,10 @@
 - grid5000_environment_export_postinstall_script: ""
 - grid5000_environment_export_postinstall_archive: ""
 - grid5000_environment_export_postinstall_compression: ""
+- grid5000_environment_export_additional_postinstall_archive: ""
+- grid5000_environment_export_additional_postinstall_compression: "gzip"
+- grid5000_environment_export_additional_postinstall_script: ""
+- grid5000_environment_export_additional_postinstall_dir: "additional_postinstall"
 - grid5000_environment_export_version: ""
 - grid5000_environment_export_author: ""
 - grid5000_environment_export_baseurl: ""
@@ -58,6 +62,9 @@
       if [ -n "$${grid5000_environment_export_postinstall_compression}" ]; then
         kaenv_postinstall_compression=1
       fi
+      if [ -n "$${grid5000_environment_export_additional_postinstall_archive}" ]; then
+        kaenv_additional_postinstall_path="$${grid5000_environment_export_baseurl}/$${grid5000_environment_export_additional_postinstall_archive}"
+      fi
       if [ -n "$${grid5000_environment_export_baseurl}" ]; then
         kaenv_image_file="$${grid5000_environment_export_baseurl}/$${kameleon_recipe_name}.$${grid5000_environment_export_format}"
       else
@@ -75,12 +82,34 @@
         ${kaenv_postinstall_script:+--modify postinstalls_script0="$${grid5000_environment_export_postinstall_script}"} \
         ${kaenv_postinstall_archive:+--modify postinstalls_archive0="$${grid5000_environment_export_postinstall_archive}"} \
         ${kaenv_postinstall_compression:+--modify postinstalls_compression0="$${grid5000_environment_export_postinstall_compression}"} \
+        ${kaenv_additional_postinstall_path:+--add-postinstall "$kaenv_additional_postinstall_path:$${grid5000_environment_export_additional_postinstall_compression}:$${grid5000_environment_export_additional_postinstall_script}"} \
         > $${grid5000_environment_export_name}.yaml
-- copy_files:
+- create_additinal_postinstall_archive:
+  - exec_local: |
+      if [ -n "$${grid5000_environment_export_additional_postinstall_archive}" ]; then
+        if [ -d "$${grid5000_environment_export_additional_postinstall_dir}" ]; then
+          echo "Creating additional postinstall archive"
+          if [ "$${grid5000_environment_export_additional_postinstall_compression}" != "gzip" ]; then
+             echo 'Error: unsupported postinstall compression format "$${grid5000_environment_export_additional_postinstall_compression}"' 1>&2
+             exit 1
+          fi
+          tar -zcvf $${grid5000_environment_export_additional_postinstall_archive} -C $${grid5000_environment_export_additional_postinstall_dir} .
+        else
+          echo 'Error: could not find "$${grid5000_environment_export_additional_postinstall_dir}"' 1>&2
+          exit 1
+        fi
+      else
+        echo "No additional postinstall"
+      fi
+- export_files:
   - exec_local: |
       if [ -n "$${grid5000_environment_export_dir}" ]; then
         echo "Copying grid5000 environment files to $${grid5000_environment_export_dir}"
         mkdir -p "$${grid5000_environment_export_dir}"
         cp -vf $${grid5000_environment_export_image_file} $${grid5000_environment_export_dir}/
         cp -vf $${grid5000_environment_export_name}.yaml $${grid5000_environment_export_dir}/
+        if [ -n "$${grid5000_environment_export_additional_postinstall_archive}" ]; then
+          cp -vf $${grid5000_environment_export_additional_postinstall_archive} \
+            $${grid5000_environment_export_dir}/$${grid5000_environment_export_additional_postinstall_archive}
+        fi
       fi
